[versions]
agp = "8.2.2"
kotlin = "1.8.10"
activity-compose = "1.7.2"
compose-compiler = "1.4.3"

minSdk = "21"
compileSdk = "34"
targetSdk = "34"
versionCode = "1"
versionName = "1.0.0"

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
lint-compose = "com.slack.lint.compose:compose-lint-checks:1.3.1"

[plugins]
android-app = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version = "1.4.1" }
gradle-nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.1.0" }