[versions]
kotlin = "1.7.20"
agp = "8.0.1"
compose-compiler = "1.3.2"

minSdk = "21"
compileSdk = "34"
targetSdk = "34"
versionCode = "1"
versionName = "1.0.0"


[libraries]

[plugins]
android-app = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
gradle-nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.1.0" }